### PR TITLE
Upgrade Dioxus to 0.5

### PR DESCRIPTION
**Pull request by anna-ahmed19**
- Upgraded Dioxus from 0.4 to 0.5
- Replaced Fermi crate with Dioxus Signals
- Upgraded all dependent crates to their latest stable versions
- Updated examples and website code to reflect the changes made in the dependent crate upgrades
- Updated README.md

[Dioxus Upgrade Issue#4](https://github.com/mrxiaozhuox/dioxus-toast/issues/4)

### CODE REVIEW

**Comment by mrxiaozhuox** [comment]
have you ever trying tot build example? I think its not work.
In old version we eed include some features in to `dioxus-toast` feature, something like: dioxus-web, dioxus-desktop. But I don't know why did you deleted it. maybe api was changed? can you tell me

**Comment by anna-ahmed19** [comment]
Hey, Thank you for your reply.
Yes, I have tried the examples, they work. 
Dioxus 0.5 has introduced a new cross platform API to launch the application.

The below is mentioned in this [Dioxus 0.5 blog](https://dioxuslabs.com/blog/release-050)

> Dioxus 0.5 introduces a new cross platform API to launch your app. This makes it easy to target multiple platforms with the same application. Instead of pulling in a separate renderer package, you can now enable a feature on the Dioxus crate and call the launch function from the prelude:

> The CLI is now smart enough to automatically pass in the appropriate build features depending on the platform you’re targeting.

Let me know any changes. Thank you.

**Comment by mrxiaozhuox** [comment]
Can you give me your command for the example execute, I want try it. if no problem I will merge it.

Thank you

**Comment by anna-ahmed19** [comment]
Hello, I was able to build the examples without including 'dioxus/desktop' and 'dioxus/web' by the below commands:
`dx build --example hello --platform desktop`
`dx build --example web --platform web -- --no-default-features`

But there was an issue in executing the examples.
I have added 'dioxus/desktop' and 'dioxus/web' in the features to resolve this.

The commands are:
`dx serve --example hello --platform desktop`
`dx serve --example web --platform web -- --no-default-features`

Looking forward to hearing from you!

**Review by mrxiaozhuox — APPROVED** [review]
Thank u!

**Comment by mrxiaozhuox** [comment]
@anna-ahmed19  I'm sorry to bother you again. I think Signal should use SignalGlobal, because I hope ToastManager can still be operated in other components and files. This is also the reason why I chose to use Fermi before, and I want to know what you think about it. Thanks.

----

Maybe I have some mistakes in understanding the new version of the API? You can tell me if you have any. For example, can Signal be passed to the downstream components in a simpler way?

**Comment by anna-ahmed19** [comment]
Hello @mrxiaozhuox 

I have tried with `GlobalSignal` for using in the `app` element like this:
`static TOAST: GlobalSignal<ToastManager> = Signal::global(|| ToastManager::default());`

But I get an error in using `GlobalSignal` in `ToastFrameProps`:
```
#[derive(Props, Clone, PartialEq)]
pub struct ToastFrameProps {
    manager: GlobalSignal<ToastManager>,
}
```
The below error occurs even after adding Clone and PartialEq in `ToastManager` and other structs: 
> the trait bound `dioxus::prelude::GlobalSignal<ToastManager>: Clone` is not satisfied
the trait `Clone` is not implemented for `dioxus::prelude::GlobalSignal<ToastManager>

That is why I used `Signal` in `ToastFrameProps`. The `use_context` and `use_context_provider` can be used to pass Signal to the downstream components in a simpler way.

**Example of use_context:**
```
fn app() -> Element {
    use_context_provider(|| Signal::new(ToastManager::default()));
    let mut toast: Signal<ToastManager> = use_context();
    rsx! {
        ToastFrame { manager: toast }
        ChildComponent{}
    }
}

fn ChildComponent() -> Element {
    let mut toast: Signal<ToastManager> = use_context();
    rsx! {
        ToastFrame { manager: toast }
    }
}
```

**Pull request merged**
